### ISSUE TITLE
Warning: Method not found: 'Void Rebus.Transport.ITransactionContext.OnCommitt

### ISSUE THREAD

**Issue by khinze** [rebus-org/Rebus.AzureStorage#12]
Hallo There,

I am trying to implement Rebus that uses azure storage queues with no luck. 
I have integrated it into my worker and it seems like the handler are not being executed on message received. 

The warning im getting:
warn: Rebus.Workers.ThreadPoolBased.ThreadPoolWorker[0]
      An error occurred when attempting to receive the next message: System.MissingMethodException: Method not found: 'Void Rebus.Transport.ITransactionContext.OnCompleted(System.Func`1<System.Threading.Tasks.Task>)'.
         at Rebus.AzureStorage.Transport.AzureStorageQueuesTransport.SetUpCompletion(ITransactionContext context, CloudQueueMessage cloudQueueMessage, CloudQueue inputQueue)
         at Rebus.AzureStorage.Transport.AzureStorageQueuesTransport.Receive(ITransactionContext context, CancellationToken cancellationToken)
         at Rebus.Workers.ThreadPoolBased.ThreadPoolWorker.ReceiveTransportMessage(CancellationToken token, ITransactionContext context)

The configuration in my worker:
 var storageAccount = CloudStorageAccount.Parse(azureStorageQueueConfiguration);
        
        services.AddRebus(configure => configure
            .Transport(t => t.UseAzureStorageQueues(storageAccount, "queue"))
            .Routing(c => c.TypeBased()
                .Map<Mycommand>("queue")
            ))
            .AddRebusHandler<MyHandler>();

I am using .net 6 with the following nuget packages:
"Rebus" Version="6.6.5"
"Rebus.AzureStorage"
"Rebus.ServiceProvider" Version="8.3.1" 

Is there something wrong in my configuration or could be that there is something missing in Azure.StorageQueues?

**Comment by mookid8000** [comment]
Closing, because I'll answer here 👉 https://github.com/rebus-org/Rebus.AzureQueues/issues/18 🙂
