### ISSUE TITLE
create stable release nuget

### ISSUE THREAD

**Issue by jr01** [rebus-org/Rebus.AzureStorage#2]
When creating a nuget that depends on rebus.azurestorage 3.0.0-b02 we get the message: "A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Rebus.AzureStorage [3.0.0-b02, )" or update the version field in the nuspec". 

Of course we can work around this, but a stable release (3.0, or 4.0...) would be much appreciated.  Is that possible, or what's the hold back?

**Comment by mookid8000** [comment]
The prerelease versioning signals that the package has not been tested to the same degree as other packages. I'm sorry, but NuGet requires that the prerelease-ness of a dependency flows further up to dependents, so you should probably just accept that your package will have to carry a prerelease version too.

If you let me know how it goes when you use it, it will help the package towards getting a real version some time.

**Comment by jr01** [comment]
Thanks for the clarification!
We only use the databus part for storing attachments in blob storage in conjunction with azure servicebus transport. It is scheduled for production in a few weeks.
