### ISSUE TITLE
Static OperationContext causes a memory leak

### ISSUE THREAD

**Issue by mlintell** [rebus-org/Rebus.AzureStorage#6]
In commit 1862883ad852f3d6b506bc2a4d8fac157919cd4a, line 38 of Rebus.AzureStorage/AzureStorage/Transport/AzureStorageQueuesTransport.cs introduced a static OperationContext. When Rebus is used in a long running service (such as a ServiceFabric service) with a DI container using Rebus.AutoFac or Rebus.ServiceProvider, this results in an ever-growing OperationContext that grows to several GB over a week or two. In our case this caused the ServiceFabric cluster to become unresponsive and eventually die. We had to rollback to 4.1.0 to resolve the issue.

**Comment by mookid8000** [comment]
Damn, I didn't know that it accumulated state. I'll fix it right away!

**Comment by mookid8000** [comment]
It'll be fixed in Rebus.AzureStorage 4.2.1, which is out in a few minutes

**Comment by mookid8000** [comment]
It's available on NuGet.org now – thanks for reporting this issue! 👍
